HIP: initRhsKernel
exactSolution
HIP_CHECK
HIPFFT_CHECK
initRhsKernel
L
main
N_RUNS
normalizeKernel
PI
poissonFourierKernel
poissonSolverCpu
poissonSolverGpu
rhsFunction
initRhsKernel()
static __global__ void initRhsKernel (hipfftDoubleComplex * d_data, size_t Nx, size_t Ny, size_t Nz) static
Initializes the RHS on the GPU.
Definition at line 217 of file fftpoisson3d.cpp.
{
    size_t i = blockIdx.x * blockDim.x + threadIdx.x;
    size_t j = blockIdx.y * blockDim.y + threadIdx.y;
    size_t k = blockIdx.z * blockDim.z + threadIdx.z;
    if (i < Nx && j < Ny && k < Nz) {
        size_t idx = (i * Ny + j) * Nz + k;
        double x = L * static_cast<double>(i) / static_cast<double>(Nx);
        double y = L * static_cast<double>(j) / static_cast<double>(Ny);
        double z = L * static_cast<double>(k) / static_cast<double>(Nz);
        d_data[idx].x = rhsFunction(x, y, z);
        d_data[idx].y = 0.0;
    }
}
References L, and rhsFunction().
Referenced by block_reduce(), f(), main(), main(), monteCarloCPU(), monteCarloGPU(), poissonSolverCpu(), and poissonSolverGpu().