HIP: main
exactSolution
HIP_CHECK
HIPFFT_CHECK
initRhsKernel
L
main
N_RUNS
normalizeKernel
PI
poissonFourierKernel
poissonSolverCpu
poissonSolverGpu
rhsFunction
main()
int main (int argc, char * argv[])
Entry point of the 3D FFT-based Poisson solver.
Definition at line 498 of file fftpoisson3d.cpp.
{
    if (argc != 4) {
        std::cerr << "Usage: " << argv[0] << " Nx Ny Nz\n";
        return EXIT_FAILURE;
    }
    size_t Nx = 0, Ny = 0, Nz = 0;
    try {
        long long temp_Nx = std::stoll(argv[1]);
        long long temp_Ny = std::stoll(argv[2]);
        long long temp_Nz = std::stoll(argv[3]);
        if (temp_Nx <= 0 || temp_Ny <= 0 || temp_Nz <= 0) {
            std::cerr << "Error: Nx, Ny, Nz must be positive integers.\n";
            return EXIT_FAILURE;
        }
        Nx = static_cast<size_t>(temp_Nx);
        Ny = static_cast<size_t>(temp_Ny);
        Nz = static_cast<size_t>(temp_Nz);
    } catch (const std::exception& e) {
        std::cerr << "Invalid input: " << e.what() << "\n";
        return EXIT_FAILURE;
    }
    const size_t N = static_cast<size_t>(Nx) * Ny * Nz;
    std::cout << "Running FFT Poisson solver with grid: "
          << Nx << " x " << Ny << " x " << Nz << " = " << N << "\n";
    // ---------------- GPU SETUP ----------------
    hipfftHandle plan_gpu;
    HIPFFT_CHECK(hipfftPlan3d(&plan_gpu, (int)Nx, (int)Ny, (int)Nz, HIPFFT_Z2Z));
    hipfftDoubleComplex* d_output;
    HIP_CHECK(hipMalloc(&d_output, N * sizeof(hipfftDoubleComplex)));
    // ---------------- GPU WARM-UP ----------------
    poissonSolverGpu(Nx, Ny, Nz, plan_gpu, d_output);
    HIP_CHECK(hipDeviceSynchronize());
    std::cout << "GPU warm-up completed.\n";
    double total_gpu_time = 0.0;
    for (size_t run = 0; run < N_RUNS; ++run) {
        auto t0_gpu = std::chrono::high_resolution_clock::now();
        poissonSolverGpu(Nx, Ny, Nz, plan_gpu, d_output);
        HIP_CHECK(hipDeviceSynchronize());
        auto t1_gpu = std::chrono::high_resolution_clock::now();
        std::chrono::duration<double> dt_gpu = t1_gpu - t0_gpu;
        total_gpu_time += dt_gpu.count();
        std::cout << "GPU run " << run+1 << " time = " << dt_gpu.count() << " s\n";
    }
    double avg_gpu_time = total_gpu_time / N_RUNS;
    // Copy GPU result to host in vector<double>
    std::vector<double> h_data(N);
    { // Use the scope to free h_temp.
        std::vector<hipfftDoubleComplex> h_temp(N);
        HIP_CHECK(hipMemcpy(h_temp.data(), d_output, N * sizeof(hipfftDoubleComplex), hipMemcpyDeviceToHost));
        std::transform(std::execution::par, h_temp.begin(), h_temp.end(), h_data.begin(),
                    [](const hipfftDoubleComplex& c){ return c.x; });
    }
    HIP_CHECK(hipFree(d_output));
    HIPFFT_CHECK(hipfftDestroy(plan_gpu));
    // ---------------- CPU SETUP ----------------
    fftw_init_threads();
    fftw_plan_with_nthreads(int(std::thread::hardware_concurrency()));
    std::ostringstream wisdom_name;
    wisdom_name << "fftpoisson3d_fftw_wisdom_"
                << Nx << "_" << Ny << "_" << Nz << ".dat";
    std::string wisdom_file = wisdom_name.str();
    bool wisdom_loaded = fftw_import_wisdom_from_filename(wisdom_file.c_str());
    if (wisdom_loaded)
        std::cout << "CPU: FFTW wisdom loaded.\n";
    else
        std::cout << "CPU: No FFTW wisdom found, plans will be measured.\n";
    fftw_complex* cpu_data = (fftw_complex*) fftw_malloc(sizeof(fftw_complex) * N);
    // ---------------- CPU WARM-UP ----------------
    poissonSolverCpu(Nx, Ny, Nz, cpu_data);
    std::cout << "CPU warm-up completed.\n";
    double total_cpu_time = 0.0;
    for (size_t run = 0; run < N_RUNS; ++run) {
        auto t0_cpu = std::chrono::high_resolution_clock::now();
        poissonSolverCpu(Nx, Ny, Nz, cpu_data);
        auto t1_cpu = std::chrono::high_resolution_clock::now();
        std::chrono::duration<double> dt_cpu = t1_cpu - t0_cpu;
        total_cpu_time += dt_cpu.count();
        std::cout << "CPU run " << run+1 << " time = " << dt_cpu.count() << " s\n";
    }
    double avg_cpu_time = total_cpu_time / N_RUNS;
    // Copy CPU solution real part into vector<double> using parallel STL
    std::vector<double> h_cpu_data(N);
    std::transform(std::execution::par, cpu_data, cpu_data + N, h_cpu_data.begin(),
                   [](const fftw_complex& c){ return c[0]; });
    if (!wisdom_loaded) {
        fftw_export_wisdom_to_filename(wisdom_file.c_str());
        std::cout << "FFTW wisdom saved to " << wisdom_file << ".\n";
    }
    fftw_cleanup_threads();
    fftw_free(cpu_data);
    // ---------------- ERROR CALCULATION ----------------
    std::vector<double> exact_u(N), gpu_errors(N), cpu_errors(N);
    std::vector<size_t> indices(N);
    std::iota(indices.begin(), indices.end(), 0);
    // ---------------- PRECOMPUTE EXACT SOLUTION ----------------
    std::transform(std::execution::par, indices.begin(), indices.end(), exact_u.begin(),
        [Nx, Ny, Nz](size_t idx){
            size_t i = idx / (Ny * Nz);
            size_t j = (idx / Nz) % Ny;
            size_t k = idx % Nz;
            return exactSolution(
                L * static_cast<double>(i) / static_cast<double>(Nx),
                L * static_cast<double>(j) / static_cast<double>(Ny),
                L * static_cast<double>(k) / static_cast<double>(Nz)
            );
        });
    // ---------------- MEAN OF EXACT SOLUTION ----------------
    double mean_exact =
        std::transform_reduce(
            std::execution::par,
            exact_u.begin(), exact_u.end(),
            0.0,
            std::plus<>(),
            [](double v){ return v; }
        ) / static_cast<double>(N);
    // ---------------- ZERO-MEAN EXACT SOLUTION ----------------
    std::for_each(std::execution::par, exact_u.begin(), exact_u.end(),
        [mean_exact](double& v){
            v -= mean_exact;
        });
    std::transform(std::execution::par, indices.begin(), indices.end(), gpu_errors.begin(),
        [&h_data, &exact_u](size_t idx){
            return std::abs(h_data[idx] - exact_u[idx]);
        });
    std::transform(std::execution::par, indices.begin(), indices.end(), cpu_errors.begin(),
        [&h_cpu_data, &exact_u](size_t idx){
            return std::abs(h_cpu_data[idx] - exact_u[idx]);
        });
    double gpu_l2 = std::transform_reduce(std::execution::par, gpu_errors.begin(), gpu_errors.end(), 0.0, std::plus<>(), [](double e){ return e*e; });
    double cpu_l2 = std::transform_reduce(std::execution::par, cpu_errors.begin(), cpu_errors.end(), 0.0, std::plus<>(), [](double e){ return e*e; });
    double gpu_max = *std::max_element(std::execution::par, gpu_errors.begin(), gpu_errors.end());
    double cpu_max = *std::max_element(std::execution::par, cpu_errors.begin(), cpu_errors.end());
    // ---------------- PRINT COMPARISON ----------------
    std::cout << "\n================== GPU vs CPU Comparison ==================\n";
    std::cout << std::left
              << std::setw(6) << "Solver" << " | "
              << std::right << std::setw(12) << "Avg Time (s)" << " | "
              << std::setw(16) << "L2 Error" << " | "
              << std::setw(16) << "Max Error" << "\n";
    std::cout << "-------|--------------|------------------|-----------------\n";
    std::cout << std::left << std::setw(6) << "GPU" << " | "
              << std::right << std::setw(12) << std::fixed << std::setprecision(6) << avg_gpu_time << " | "
              << std::setw(16) << std::scientific << std::setprecision(6) << std::sqrt(gpu_l2/(double)N) << " | "
              << std::setw(16) << std::scientific << std::setprecision(6) << gpu_max << "\n";
    std::cout << std::left << std::setw(6) << "CPU" << " | "
              << std::right << std::setw(12) << std::fixed << std::setprecision(6) << avg_cpu_time << " | "
              << std::setw(16) << std::scientific << std::setprecision(6) << std::sqrt(cpu_l2/double(N)) << " | "
              << std::setw(16) << std::scientific << std::setprecision(6) << cpu_max << "\n";
    std::cout << "===========================================================\n";
    return EXIT_SUCCESS;
}
References HIP_CHECK, HIPFFT_CHECK, initRhsKernel(), N, N_RUNS, poissonSolverCpu(), and poissonSolverGpu().