HIP: f
CPU_SAMPLES_PER_ITER
f
HIP_CHECK
main
monteCarloCPU
monteCarloGPU
N
THREADS_PER_BLOCK
f()
__host__ __device__ double f (double x, double y, double z) inline
Function to be integrated over the unit cube [0,1]^3.
This function is evaluated on both CPU and GPU.
Parameters
x First coordinate in [0,1]
y Second coordinate in [0,1]
z Third coordinate in [0,1]
Returns
Value of the integrand at (x, y, z)
Definition at line 98 of file montecarlointegration.cpp.
{
    return std::exp(-(x * x + y * y + z * z))
         * std::sin(5.0 * x)
         * std::cos(5.0 * y)
         * std::sin(5.0 * z);
}
References initRhsKernel().
Referenced by monteCarloCPU(), and monteCarloGPU().