HIP: main
CPU_SAMPLES_PER_ITER
f
HIP_CHECK
main
monteCarloCPU
monteCarloGPU
N
THREADS_PER_BLOCK
main()
int main ()
Main function performing CPU and GPU Monte Carlo integration.
Execution steps:
Allocate and initialize GPU memory.
Launch GPU Monte Carlo kernel and measure execution time.
Copy GPU result back to host and normalize.
Perform CPU Monte Carlo integration and measure execution time.
Print results and timing information.
Returns
int Returns 0 on successful execution.
Definition at line 202 of file montecarlointegration.cpp.
           {
    // ============================================================
    // GPU Monte Carlo
    // ============================================================
    double* d_result = nullptr;
    HIP_CHECK(hipMalloc(&d_result, sizeof(double)));
    HIP_CHECK(hipMemset(d_result, 0, sizeof(double)));
    hipDeviceProp_t prop;
    HIP_CHECK(hipGetDeviceProperties(&prop, 0));
    const std::size_t threads = THREADS_PER_BLOCK;
    const std::size_t blocks = std::min(
        (N + threads - 1) / threads,
        static_cast<std::size_t>(prop.multiProcessorCount) * 64
    );
    std::cout << "GPU config: "
              << blocks << " blocks x "
              << threads << " threads\n";
    auto gpu_start = std::chrono::high_resolution_clock::now();
    hipLaunchKernelGGL(
        monteCarloGPU,
        dim3(static_cast<unsigned int>(blocks)),
        dim3(static_cast<unsigned int>(threads)),
        0, 0,
        d_result, N, 1234ULL
    );
    HIP_CHECK(hipGetLastError());
    HIP_CHECK(hipDeviceSynchronize());
    double gpu_sum = 0.0;
    HIP_CHECK(hipMemcpy(&gpu_sum, d_result,
                        sizeof(double),
                        hipMemcpyDeviceToHost));
    auto gpu_end = std::chrono::high_resolution_clock::now();
    double gpu_time_s =
        std::chrono::duration<double>(gpu_end - gpu_start).count();
    std::cout << "GPU result: "
              << gpu_sum / static_cast<double>(N)
              << " in " << gpu_time_s << " s\n";
    HIP_CHECK(hipFree(d_result));
    // ============================================================
    // CPU Monte Carlo
    // ============================================================
    auto cpu_start = std::chrono::high_resolution_clock::now();
    double cpu_result = monteCarloCPU(N, CPU_SAMPLES_PER_ITER);
    auto cpu_end = std::chrono::high_resolution_clock::now();
    double cpu_time_s =
        std::chrono::duration<double>(cpu_end - cpu_start).count();
    std::cout << "CPU result: "
              << cpu_result
              << " in " << cpu_time_s << " s\n";
    return EXIT_SUCCESS;
}
References CPU_SAMPLES_PER_ITER, HIP_CHECK, initRhsKernel(), monteCarloCPU(), monteCarloGPU(), N, and THREADS_PER_BLOCK.