HIP: monteCarloGPU
CPU_SAMPLES_PER_ITER
f
HIP_CHECK
main
monteCarloCPU
monteCarloGPU
N
THREADS_PER_BLOCK
monteCarloGPU()
static __global__ void monteCarloGPU (double * result, std::size_t num_samples, unsigned long long seed) static
GPU kernel for Monte Carlo integration.
Each thread generates random samples using hipRAND and accumulates a partial sum, which is added atomically to the global result.
Parameters
result Pointer to global result accumulator
num_samples Total number of Monte Carlo samples
seed Random seed for hipRAND
Definition at line 163 of file montecarlointegration.cpp.
{
    const std::size_t idx =
        blockIdx.x * blockDim.x + threadIdx.x;
    const std::size_t stride =
        gridDim.x * blockDim.x;
    hiprandStatePhilox4_32_10_t state;
    hiprand_init(seed, idx, 0, &state);
    double local_sum = 0.0;
    for (std::size_t i = idx; i < num_samples; i += stride) {
        local_sum += f(
            hiprand_uniform_double(&state),
            hiprand_uniform_double(&state),
            hiprand_uniform_double(&state)
        );
    }
    atomicAdd(result, local_sum);
}
References f(), and initRhsKernel().
Referenced by main().